// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA73CubqAyM5AtIGNibDxA2mMqnxczT7LM',
    appId: '1:625428199700:web:e10f193c66adf6f1cdaa01',
    messagingSenderId: '625428199700',
    projectId: 'mahdi-pfe',
    authDomain: 'mahdi-pfe.firebaseapp.com',
    storageBucket: 'mahdi-pfe.firebasestorage.app',
    databaseURL: 'https://mahdi-pfe-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMB85P8m7Ni11ESXLFIWh9rZKg0k4WRqg',
    appId: '1:625428199700:android:28ed3a0e6ef75d2acdaa01',
    messagingSenderId: '625428199700',
    projectId: 'mahdi-pfe',
    storageBucket: 'mahdi-pfe.firebasestorage.app',
    databaseURL: 'https://mahdi-pfe-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA73CubqAyM5AtIGNibDxA2mMqnxczT7LM',
    appId: '1:625428199700:web:e10f193c66adf6f1cdaa01',
    messagingSenderId: '625428199700',
    projectId: 'mahdi-pfe',
    storageBucket: 'mahdi-pfe.firebasestorage.app',
    databaseURL: 'https://mahdi-pfe-default-rtdb.europe-west1.firebasedatabase.app',
    iosBundleId: 'com.example.tracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA73CubqAyM5AtIGNibDxA2mMqnxczT7LM',
    appId: '1:625428199700:web:e10f193c66adf6f1cdaa01',
    messagingSenderId: '625428199700',
    projectId: 'mahdi-pfe',
    storageBucket: 'mahdi-pfe.firebasestorage.app',
    databaseURL: 'https://mahdi-pfe-default-rtdb.europe-west1.firebasedatabase.app',
    iosBundleId: 'com.example.tracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA73CubqAyM5AtIGNibDxA2mMqnxczT7LM',
    appId: '1:625428199700:web:e10f193c66adf6f1cdaa01',
    messagingSenderId: '625428199700',
    projectId: 'mahdi-pfe',
    authDomain: 'mahdi-pfe.firebaseapp.com',
    storageBucket: 'mahdi-pfe.firebasestorage.app',
    databaseURL: 'https://mahdi-pfe-default-rtdb.europe-west1.firebasedatabase.app',
  );
}
